# Generated by Django 5.0.1 on 2024-02-20 15:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('basic_html', models.FileField(max_length=255, upload_to='')),
                ('data_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('company_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_duration', models.IntegerField()),
                ('contract_periods', models.CharField(choices=[('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], default='Weeks', max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('onboarding_date', models.DateField()),
                ('company_address', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('s3_file_link', models.CharField(max_length=255)),
            ],
        ),
    ]
