# Generated by Django 5.0.1 on 2024-09-24 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiduciaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='uploads/reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_plan_type', models.CharField(max_length=255, verbose_name='Type of Account (Current Plan)')),
                ('current_account_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Account Value (Current Plan)')),
                ('current_aum_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='AUM Fee % (Current Plan)')),
                ('current_expenses', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Expenses % (Current Plan)')),
                ('current_total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Current Cost')),
                ('recommended_plan_type', models.CharField(max_length=255, verbose_name='Type of Account (Recommended IRA)')),
                ('recommended_account_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Account Value (Recommended IRA)')),
                ('recommended_aum_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='AUM Fee % (Recommended IRA)')),
                ('recommended_expenses', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Expenses % (Recommended IRA)')),
                ('recommended_total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total New Cost')),
                ('value_justification', models.BooleanField(default=False, verbose_name='Does the value justify the fees for the recommended IRA?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('fiduciaryreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_comparison', to='fiduciary.fiduciaryreport')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_planning_services', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='Interested in Financial or Estate Planning Services')),
                ('investment_management', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='Prefers discretionary investment management vs making their own investment decisions')),
                ('updates_advice_monitoring', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='Wants consistent updates, advice, and monitoring')),
                ('tax_strategy_planning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='Interested in Tax strategy and planning')),
                ('education_training', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='Interested in education, training, and seminars')),
                ('additional_requirements_choice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='Additional Requirements')),
                ('additional_requirements_text', models.TextField(blank=True, null=True, verbose_name='Enter any additional requirements')),
                ('notes', models.TextField(blank=True, null=True)),
                ('fiduciaryreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_requirements', to='fiduciary.fiduciaryreport')),
            ],
        ),
        migrations.CreateModel(
            name='NewPlanRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_ira_name', models.CharField(max_length=255, verbose_name='Name of Proposed IRA')),
                ('proposed_total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Costs')),
                ('proposed_avg_rate_of_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rate of Return')),
                ('proposed_investments_available', models.CharField(max_length=255, verbose_name='Investments Available')),
                ('proposed_risk_category', models.CharField(max_length=255, verbose_name='Risk Category')),
                ('peer1_ira_name', models.CharField(max_length=255, verbose_name='Name of Peer 1 IRA')),
                ('peer1_total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Costs (Peer 1)')),
                ('peer1_avg_rate_of_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rate of Return (Peer 1)')),
                ('peer1_investments_available', models.CharField(max_length=255, verbose_name='Investments Available (Peer 1)')),
                ('peer1_risk_category', models.CharField(max_length=255, verbose_name='Risk Category (Peer 1)')),
                ('peer2_ira_name', models.CharField(max_length=255, verbose_name='Name of Peer 2 IRA')),
                ('peer2_total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Costs (Peer 2)')),
                ('peer2_avg_rate_of_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rate of Return (Peer 2)')),
                ('peer2_investments_available', models.CharField(max_length=255, verbose_name='Investments Available (Peer 2)')),
                ('peer2_risk_category', models.CharField(max_length=255, verbose_name='Risk Category (Peer 2)')),
                ('peer3_ira_name', models.CharField(max_length=255, verbose_name='Name of Peer 3 IRA')),
                ('peer3_total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Costs (Peer 3)')),
                ('peer3_avg_rate_of_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rate of Return (Peer 3)')),
                ('peer3_investments_available', models.CharField(max_length=255, verbose_name='Investments Available (Peer 3)')),
                ('peer3_risk_category', models.CharField(max_length=255, verbose_name='Risk Category (Peer 3)')),
                ('value_proposition', models.TextField(blank=True, null=True, verbose_name="Firm's Value Proposition")),
                ('best_interest_reason', models.TextField(blank=True, null=True, verbose_name='Why is this Selection in the Best Interest of the Client?')),
                ('fiduciaryreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_recommendations', to='fiduciary.fiduciaryreport')),
            ],
        ),
        migrations.CreateModel(
            name='PlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('current_plan', models.BooleanField(default=False)),
                ('recommended_ira', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fiduciaryreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_services', to='fiduciary.fiduciaryreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('advisor_full_name', models.CharField(blank=True, max_length=255)),
                ('date_prepared', models.DateField()),
                ('type_of_client', models.CharField(choices=[('New', 'New'), ('Current', 'Current'), ('Former', 'Former')], max_length=50)),
                ('client_risk_tolerance', models.CharField(choices=[('Aggressive', 'Aggressive'), ('Moderate', 'Moderate'), ('Conservative', 'Conservative')], max_length=50)),
                ('investment_objective', models.CharField(choices=[('Growth', 'Growth'), ('Income', 'Income'), ('Preservation', 'Preservation'), ('Growth & Income', 'Growth & Income')], max_length=50)),
                ('timeline', models.CharField(choices=[('0-5 Years', '0-5 Years'), ('5-10 Years', '5-10 Years'), ('10-15 Years', '10-15 Years'), ('15+ Years', '15+ Years')], max_length=50)),
                ('type_of_plan', models.CharField(choices=[('Plan to IRA', 'Plan to IRA'), ('IRA to IRA', 'IRA to IRA')], max_length=100)),
                ('reason_for_rollover', models.CharField(choices=[('Plan Termination', 'Plan Termination'), ('Transfer', 'Transfer')], max_length=50)),
                ('client_goals', models.CharField(choices=[('Retirement', 'Retirement'), ('Travel', 'Travel'), ('Hobbies', 'Hobbies'), ('Accumulation', 'Accumulation'), ('Education', 'Education'), ('Estate Planning', 'Estate Planning'), ('Real Estate', 'Real Estate')], max_length=50)),
                ('advisor_notes', models.TextField(blank=True, null=True)),
                ('fiduciaryreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_details', to='fiduciary.fiduciaryreport')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesReviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_fee_data', models.BooleanField(default=False, verbose_name='404(a) Plan and Fee Data')),
                ('form_5500', models.BooleanField(default=False, verbose_name='Form 5500')),
                ('benchmark_data', models.BooleanField(default=False, verbose_name='Benchmark Data')),
                ('quarterly_account_statements', models.BooleanField(default=False, verbose_name='Quarterly Account Statements')),
                ('summary_plan_description', models.BooleanField(default=False, verbose_name='Summary Plan Description')),
                ('investment_comparative_chart', models.BooleanField(default=False, verbose_name='Investment Comparative Chart')),
                ('ips', models.BooleanField(default=False, verbose_name='IPS')),
                ('other_description', models.TextField(blank=True, null=True, verbose_name='Other, Please Describe Below')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='uploads/documents/')),
                ('fiduciaryreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources_reviewed', to='fiduciary.fiduciaryreport')),
            ],
        ),
    ]
