# Generated by Django 5.0.1 on 2024-09-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiduciaryreport',
            name='title',
        ),
    ]
