# Generated by Django 5.0.1 on 2024-09-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0002_remove_fiduciaryreport_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrospectiveKeyReviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetrospectiveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_report', models.PositiveIntegerField()),
                ('previous_plan_type', models.CharField(max_length=255, verbose_name='Previous Plan Type')),
                ('recommended_plan_type', models.CharField(max_length=255, verbose_name='Recommended Plan Type')),
                ('disclosures_delivered', models.BooleanField(default=False, verbose_name='Disclosures Delivered?')),
                ('alternative_plans_presented', models.BooleanField(default=False, verbose_name='Alternative Plans Presented?')),
                ('fee_services_analysis', models.BooleanField(default=False, verbose_name='Fee & Services Analysis?')),
                ('best_interest_recommendation', models.BooleanField(default=False, verbose_name='Recommendation in the best interest of the client?')),
                ('fiduciary_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective_reviews', to='fiduciary.fiduciaryreport')),
            ],
        ),
        migrations.CreateModel(
            name='RetrospectiveKeyReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiduciary.retrospectivekeyreviewquestion')),
                ('retrospective_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fiduciary.retrospectivereview')),
            ],
        ),
    ]
