# Generated by Django 5.0.1 on 2024-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0003_retrospectivekeyreviewquestion_retrospectivereview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='previous_plan_type',
        ),
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='recommended_plan_type',
        ),
        migrations.AddField(
            model_name='retrospectivereview',
            name='notes',
            field=models.BooleanField(default=False, verbose_name='notes'),
        ),
    ]
