# Generated by Django 5.0.1 on 2024-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0004_remove_retrospectivereview_previous_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrospectivereview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
