# Generated by Django 5.0.1 on 2024-09-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0005_alter_retrospectivereview_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospectivekeyreviewanswer',
            name='retrospective_review',
        ),
    ]
