# Generated by Django 5.0.1 on 2024-09-25 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0006_remove_retrospectivekeyreviewanswer_retrospective_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='alternative_plans_presented',
        ),
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='best_interest_recommendation',
        ),
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='disclosures_delivered',
        ),
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='fee_services_analysis',
        ),
        migrations.RemoveField(
            model_name='retrospectivereview',
            name='notes',
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='alternative_plans_presented',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Alternative Plans Presented?'),
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='best_interest_recommendation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Recommendation in the best interest of the client?'),
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='disclosures_delivered',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Disclosures Delivered?'),
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='fee_services_analysis',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fee & Services Analysis?'),
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrospectivekeyreviewanswer',
            name='retrospective_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fiduciary.retrospectivereview'),
        ),
    ]
