# Generated by Django 5.0.1 on 2024-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0007_remove_retrospectivereview_alternative_plans_presented_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiduciaryreport',
            name='report_file',
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='s3_file_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
