# Generated by Django 5.0.1 on 2024-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0008_remove_fiduciaryreport_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospectivekeyreviewanswer',
            name='retrospective_review',
        ),
        migrations.AddField(
            model_name='retrospectivekeyreviewanswer',
            name='year_of_report',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RetrospectiveReview',
        ),
    ]
