# Generated by Django 5.0.1 on 2024-09-26 11:05

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0009_remove_retrospectivekeyreviewanswer_retrospective_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secret_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 10, 3, 11, 5, 39, 161558, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
