# Generated by Django 5.0.1 on 2024-09-30 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0010_signupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 14, 20, 40, 731491, tzinfo=datetime.timezone.utc)),
        ),
    ]
