# Generated by Django 5.0.1 on 2024-09-30 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0011_alter_signupinvitation_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcomparison',
            name='current_account_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Account Value (Current Plan)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='current_aum_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AUM Fee % (Current Plan)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='current_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Expenses % (Current Plan)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='current_plan_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Account (Current Plan)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='current_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Current Cost'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='recommended_account_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Account Value (Recommended IRA)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='recommended_aum_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AUM Fee % (Recommended IRA)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='recommended_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Expenses % (Recommended IRA)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='recommended_plan_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Account (Recommended IRA)'),
        ),
        migrations.AlterField(
            model_name='costcomparison',
            name='recommended_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total New Cost'),
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 16, 46, 43, 883363, tzinfo=datetime.timezone.utc)),
        ),
    ]
