# Generated by Django 5.0.1 on 2024-09-30 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0012_alter_costcomparison_current_account_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer1_avg_rate_of_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average Rate of Return (Peer 1)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer1_investments_available',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investments Available (Peer 1)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer1_ira_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Peer 1 IRA'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer1_risk_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Risk Category (Peer 1)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer1_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Costs (Peer 1)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer2_avg_rate_of_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average Rate of Return (Peer 2)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer2_investments_available',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investments Available (Peer 2)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer2_ira_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Peer 2 IRA'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer2_risk_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Risk Category (Peer 2)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer2_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Costs (Peer 2)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer3_avg_rate_of_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average Rate of Return (Peer 3)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer3_investments_available',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investments Available (Peer 3)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer3_ira_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Peer 3 IRA'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer3_risk_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Risk Category (Peer 3)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='peer3_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Costs (Peer 3)'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='proposed_avg_rate_of_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average Rate of Return'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='proposed_investments_available',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investments Available'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='proposed_ira_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Proposed IRA'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='proposed_risk_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Risk Category'),
        ),
        migrations.AlterField(
            model_name='newplanrecommendation',
            name='proposed_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Costs'),
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 16, 49, 21, 642275, tzinfo=datetime.timezone.utc)),
        ),
    ]
