# Generated by Django 5.0.1 on 2024-10-01 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0013_alter_newplanrecommendation_peer1_avg_rate_of_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiduciaryreport',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 7, 35, 8, 857329, tzinfo=datetime.timezone.utc)),
        ),
    ]
