# Generated by Django 5.0.1 on 2024-10-01 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0014_fiduciaryreport_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportclientdetails',
            name='advisor_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='client_goals',
            field=models.CharField(blank=True, choices=[('Retirement', 'Retirement'), ('Travel', 'Travel'), ('Hobbies', 'Hobbies'), ('Accumulation', 'Accumulation'), ('Education', 'Education'), ('Estate Planning', 'Estate Planning'), ('Real Estate', 'Real Estate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='client_risk_tolerance',
            field=models.CharField(blank=True, choices=[('Aggressive', 'Aggressive'), ('Moderate', 'Moderate'), ('Conservative', 'Conservative')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='date_prepared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='investment_objective',
            field=models.CharField(blank=True, choices=[('Growth', 'Growth'), ('Income', 'Income'), ('Preservation', 'Preservation'), ('Growth & Income', 'Growth & Income')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='reason_for_rollover',
            field=models.CharField(blank=True, choices=[('Plan Termination', 'Plan Termination'), ('Transfer', 'Transfer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='timeline',
            field=models.CharField(blank=True, choices=[('0-5 Years', '0-5 Years'), ('5-10 Years', '5-10 Years'), ('10-15 Years', '10-15 Years'), ('15+ Years', '15+ Years')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='type_of_client',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Current', 'Current'), ('Former', 'Former')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportclientdetails',
            name='type_of_plan',
            field=models.CharField(blank=True, choices=[('Plan to IRA', 'Plan to IRA'), ('IRA to IRA', 'IRA to IRA')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 7, 59, 6, 239704, tzinfo=datetime.timezone.utc)),
        ),
    ]
