# Generated by Django 5.0.1 on 2024-10-01 15:51

import django.db.models.deletion
import fiduciary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0015_alter_reportclientdetails_advisor_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_text', models.TextField()),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralReportPlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='additional_requirements_choice',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='additional_requirements_text',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='education_training',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='estate_planning_services',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='investment_management',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='tax_strategy_planning',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='updates_advice_monitoring',
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=fiduciary.models.get_expiration_date),
        ),
        migrations.AddField(
            model_name='clientrequirements',
            name='requirements',
            field=models.ManyToManyField(related_name='client_requirements', to='fiduciary.clientrequirement'),
        ),
        migrations.CreateModel(
            name='ReportPlanServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_plan', models.BooleanField(default=False)),
                ('recommended_ira', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fiduciaryreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_services', to='fiduciary.fiduciaryreport')),
                ('general_plan_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_plan_services', to='fiduciary.generalreportplanservice')),
            ],
        ),
        migrations.DeleteModel(
            name='PlanService',
        ),
    ]
