# Generated by Django 5.0.1 on 2024-10-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0016_clientrequirement_generalreportplanservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneralClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CostComparison',
            new_name='ReportCostComparison',
        ),
        migrations.RenameModel(
            old_name='NewPlanRecommendation',
            new_name='ReportNewPlanRecommendation',
        ),
        migrations.RenameModel(
            old_name='ResourcesReviewed',
            new_name='ReportResourcesReviewed',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='clientrequirements',
            name='fiduciaryreport',
        ),
        migrations.CreateModel(
            name='ReportClientRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, null=True)),
                ('fiduciaryreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_requirements', to='fiduciary.fiduciaryreport')),
                ('requirements', models.ManyToManyField(related_name='client_requirements', to='fiduciary.reportgeneralclientrequirement')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientRequirement',
        ),
        migrations.DeleteModel(
            name='ClientRequirements',
        ),
    ]
