# Generated by Django 5.0.1 on 2024-10-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0017_reportgeneralclientrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportclientrequirements',
            name='requirements',
        ),
        migrations.AddField(
            model_name='reportclientrequirements',
            name='general_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_requirements', to='fiduciary.reportgeneralclientrequirement'),
        ),
        migrations.AlterField(
            model_name='reportclientrequirements',
            name='fiduciaryreport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requirements', to='fiduciary.fiduciaryreport'),
        ),
        migrations.AlterField(
            model_name='reportclientrequirements',
            name='status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Uncertain', 'Uncertain')], max_length=10, null=True, verbose_name='status'),
        ),
    ]
