# Generated by Django 5.0.1 on 2024-10-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0018_remove_reportclientrequirements_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportclientrequirements',
            name='general_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_client_requirements', to='fiduciary.reportgeneralclientrequirement'),
        ),
    ]
