# Generated by Django 5.0.1 on 2024-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0019_alter_reportclientrequirements_general_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiduciaryreport',
            name='cover_page',
            field=models.TextField(blank=True, null=True, verbose_name='Cover Page'),
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='disclosures',
            field=models.TextField(blank=True, null=True, verbose_name='Disclosures'),
        ),
        migrations.AddField(
            model_name='fiduciaryreport',
            name='introduction_page',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction Page'),
        ),
    ]
