# Generated by Django 5.0.1 on 2024-10-03 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0020_fiduciaryreport_cover_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreportplanservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportgeneralclientrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_requirements', to=settings.AUTH_USER_MODEL),
        ),
    ]
