# Generated by Django 5.0.1 on 2024-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0021_generalreportplanservice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectivekeyreviewanswer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
