# Generated by Django 5.0.1 on 2024-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0022_retrospectivekeyreviewanswer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportclientdetails',
            name='reason_for_rollover',
            field=models.CharField(blank=True, choices=[('Plan Termination', 'Plan Termination'), ('Transfer', 'Transfer'), ('Retired', 'Retired')], max_length=50, null=True),
        ),
    ]
