# Generated by Django 5.0.1 on 2024-10-11 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0023_alter_reportclientdetails_reason_for_rollover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectivekeyreviewanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
