# Generated by Django 5.0.1 on 2024-10-16 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0024_retrospectivekeyreviewanswer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresourcesreviewed',
            name='additional_documents',
        ),
        migrations.AddField(
            model_name='reportresourcesreviewed',
            name='additional_document_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
