# Generated by Django 5.0.1 on 2024-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0025_remove_reportresourcesreviewed_additional_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportplanservices',
            name='current_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reportplanservices',
            name='recommended_ira',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
