# Generated by Django 5.0.1 on 2024-06-24 11:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('schedule_date', models.DateField()),
                ('due_date', models.DateField()),
                ('additional_tags', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('answer_data', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Twice a Year', 'Twice a Year')], default='Yearly', max_length=20)),
                ('quarter_ending', models.CharField(choices=[('January', 'January'), ('March', 'March'), ('June', 'June'), ('September', 'September'), ('December', 'December'), ('Empty', 'Empty')], default='Empty', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_file_s3_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, default=list, size=None)),
                ('template_json_data', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Overdue', 'Overdue')], default='Upcoming', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
