# Generated by Django 5.0.1 on 2024-07-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_data', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='organizationtask',
            name='task_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskhistory'),
        ),
    ]
