# Generated by Django 5.0.1 on 2024-07-09 09:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('task', '0002_taskhistory_organizationtask_task_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtask',
            name='organization_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organizationtask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
