# Generated by Django 5.0.1 on 2024-07-11 07:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('task', '0003_organizationtask_organization_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtask',
            name='organization_users',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quarter_ending',
        ),
        migrations.CreateModel(
            name='OrganizationUserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_file_s3_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, default=list, size=None)),
                ('template_json_data', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Overdue', 'Overdue')], default='Upcoming', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('task_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskhistory')),
            ],
        ),
    ]
