# Generated by Django 5.0.1 on 2024-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_organizationtask_organization_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtask',
            name='task_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Overdue', 'Overdue'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationusertask',
            name='task_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Overdue', 'Overdue'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Upcoming', max_length=20),
        ),
    ]
