# Generated by Django 5.0.1 on 2024-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_organizationtask_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency_due_date',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
