# Generated by Django 5.0.1 on 2024-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_organizationtask_resource_file_s3_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manual_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
