# Generated by Django 5.0.1 on 2024-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_manual_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtask',
            name='task_report_link',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtask',
            name='user_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organizationusertask',
            name='task_report_link',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationusertask',
            name='user_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
