# Generated by Django 5.0.1 on 2024-08-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_organizationtask_task_report_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtask',
            name='user_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='organizationusertask',
            name='user_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
