# Generated by Django 5.0.1 on 2024-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_organizationtask_user_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtask',
            name='task_report_link',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='organizationusertask',
            name='task_report_link',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
