# Generated by Django 5.0.1 on 2024-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_organizationtask_task_report_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='s3_file_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
