# Generated by Django 5.0.1 on 2024-11-06 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_task_s3_file_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtask',
            name='resource_file_s3_links',
        ),
        migrations.RemoveField(
            model_name='organizationtask',
            name='task_report_link',
        ),
        migrations.RemoveField(
            model_name='organizationtask',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='organizationtask',
            name='template_json_data',
        ),
        migrations.RemoveField(
            model_name='organizationtask',
            name='user_list',
        ),
        migrations.RemoveField(
            model_name='organizationusertask',
            name='resource_file_s3_links',
        ),
        migrations.RemoveField(
            model_name='organizationusertask',
            name='task_report_link',
        ),
        migrations.RemoveField(
            model_name='organizationusertask',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='organizationusertask',
            name='template_json_data',
        ),
        migrations.RemoveField(
            model_name='organizationusertask',
            name='user_list',
        ),
        migrations.AddField(
            model_name='task',
            name='resource_file_s3_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_report_link',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Overdue', 'Overdue'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='template_json_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
