# Generated by Django 5.0.1 on 2024-11-07 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_remove_organizationtask_resource_file_s3_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
