# Generated by Django 5.0.1 on 2024-11-07 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
