# Generated by Django 5.0.1 on 2024-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_task_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
