# Generated by Django 5.0.1 on 2024-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_remove_organizationtask_task_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('cco', 'CCO')], max_length=10, null=True),
        ),
    ]
