# Generated by Django 5.0.1 on 2024-11-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_deletedtaskhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedTaskHistory',
        ),
    ]
