# Generated by Django 5.0.1 on 2024-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_task_completed_at_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
