# Generated by Django 5.0.1 on 2024-11-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('task', '0023_deletedtaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedtaskhistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='deletedtaskhistory',
            name='reason_for_deletion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
