# Generated by Django 5.0.1 on 2024-02-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationParentNavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=300)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.navbar')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SubNavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('display_name', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.TextField()),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSubNavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.navbar')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('subnavbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.subnavbar')),
            ],
        ),
    ]
