# Generated by Django 5.0.1 on 2024-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrulelinks',
            name='rule_name',
            field=models.CharField(choices=[('Final Rules', 'Final Rules'), ('Proposed Rules', 'Proposed Rules'), ('Enforcement Actions', 'Enforcement Actions'), ('Risk Alerts', 'Risk Alerts'), ('Press Releases', 'Press Releases')], max_length=20),
        ),
    ]
