# Generated by Django 5.0.1 on 2024-08-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0003_alter_regulatoryreview_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessmentquestion',
            old_name='text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='riskassessmentsection',
            old_name='name',
            new_name='section',
        ),
    ]
