# Generated by Django 5.0.1 on 2024-08-07 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0004_rename_text_riskassessmentquestion_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentquestion',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='riskassessmentsection',
            name='section',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='riskassessmentquestion',
            constraint=models.UniqueConstraint(fields=('question',), name='unique_question'),
        ),
        migrations.AddConstraint(
            model_name='riskassessmentsection',
            constraint=models.UniqueConstraint(fields=('section',), name='unique_section'),
        ),
    ]
