# Generated by Django 5.0.1 on 2024-08-07 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0005_alter_riskassessmentquestion_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='riskassessmentquestion',
            name='unique_question',
        ),
        migrations.AlterField(
            model_name='riskassessmentquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='riskassessmentquestion',
            constraint=models.UniqueConstraint(fields=('section', 'question'), name='unique_section_question'),
        ),
    ]
