# Generated by Django 5.0.1 on 2024-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0006_remove_riskassessmentquestion_unique_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentorgquestionresponse',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessmentquestion',
            name='no_score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='riskassessmentquestion',
            name='yes_score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
