# Generated by Django 5.0.1 on 2024-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0007_riskassessmentorgquestionresponse_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentorgquestionresponse',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
