# Generated by Django 5.0.1 on 2024-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0008_alter_riskassessmentorgquestionresponse_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentorgaveragescore',
            name='average_score',
            field=models.FloatField(),
        ),
    ]
