# Generated by Django 5.0.1 on 2024-08-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0009_alter_riskassessmentorgaveragescore_average_score'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentorgaveragescore',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_scores', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='riskassessmentorgquestionresponse',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='organization.organization'),
        ),
    ]
