# Generated by Django 5.0.1 on 2024-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0010_alter_riskassessmentorgaveragescore_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryreview',
            name='attached_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulatoryreview',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulatoryreview',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulatoryreview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
