# Generated by Django 5.0.1 on 2024-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0011_alter_regulatoryreview_attached_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentorgquestionresponse',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
