# Generated by Django 5.0.1 on 2024-08-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0012_riskassessmentorgquestionresponse_note'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliciesAndProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_procedure_section', models.CharField(blank=True, max_length=255, null=True)),
                ('work_flow_link', models.JSONField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('regulatory_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acr_tool.regulatoryreview')),
                ('risk_questions', models.ManyToManyField(blank=True, null=True, to='acr_tool.riskassessmentquestion')),
                ('risk_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acr_tool.riskassessmentsection')),
            ],
        ),
    ]
