# Generated by Django 5.0.1 on 2024-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0013_policiesandprocedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandprocedures',
            name='risk_questions',
            field=models.ManyToManyField(blank=True, to='acr_tool.riskassessmentquestion'),
        ),
    ]
