# Generated by Django 5.0.1 on 2024-08-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0014_alter_policiesandprocedures_risk_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryreview',
            name='regulatory_updates',
        ),
        migrations.CreateModel(
            name='RegulatoryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('regulatory_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_updates', to='acr_tool.regulatoryreview')),
            ],
        ),
    ]
