# Generated by Django 5.0.1 on 2024-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0015_remove_regulatoryreview_regulatory_updates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryupdate',
            name='regulatory_review',
        ),
        migrations.AddField(
            model_name='regulatoryreview',
            name='regulatory_updates',
            field=models.ManyToManyField(blank=True, related_name='regulatory_reviews', to='acr_tool.regulatoryupdate'),
        ),
    ]
