# Generated by Django 5.0.1 on 2024-08-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0016_remove_regulatoryupdate_regulatory_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryreview',
            name='regulatory_updates',
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('rule_order', models.IntegerField()),
                ('regulatory_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_rules', to='acr_tool.regulatoryreview')),
            ],
        ),
        migrations.DeleteModel(
            name='RegulatoryUpdate',
        ),
    ]
