# Generated by Django 5.0.1 on 2024-08-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0017_remove_regulatoryreview_regulatory_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryrule',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-08-08'),
            preserve_default=False,
        ),
    ]
