# Generated by Django 5.0.1 on 2024-08-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0019_remove_policiesandprocedures_regulatory_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryrule',
            name='regulatory_review',
        ),
    ]
