# Generated by Django 5.0.1 on 2024-08-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0020_remove_regulatoryrule_regulatory_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryrule',
            name='regulatory_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acr_tool.regulatoryreview'),
            preserve_default=False,
        ),
    ]
