# Generated by Django 5.0.1 on 2024-08-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0021_regulatoryrule_regulatory_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policiesandprocedures',
            name='regulatory_rule',
        ),
        migrations.AddField(
            model_name='policiesandprocedures',
            name='regulatory_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acr_tool.regulatoryreview'),
        ),
    ]
