# Generated by Django 5.0.1 on 2024-08-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0022_remove_policiesandprocedures_regulatory_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandprocedures',
            name='regulatory_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acr_tool.regulatoryrule'),
        ),
    ]
