# Generated by Django 5.0.1 on 2024-08-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0023_alter_policiesandprocedures_regulatory_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policiesandprocedures',
            old_name='regulatory_review',
            new_name='regulatory_rule',
        ),
    ]
