# Generated by Django 5.0.1 on 2024-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0024_rename_regulatory_review_policiesandprocedures_regulatory_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryreview',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-08-22'),
            preserve_default=False,
        ),
    ]
