# Generated by Django 5.0.1 on 2024-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0025_regulatoryreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryrule',
            name='rule_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
