# Generated by Django 5.0.1 on 2024-08-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0027_procedurereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedurereview',
            old_name='completed_task',
            new_name='task',
        ),
    ]
