# Generated by Django 5.0.1 on 2024-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0028_rename_completed_task_procedurereview_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandprocedures',
            name='work_flow_link',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='procedurereview',
            name='compliance_calender_report_link',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
