# Generated by Django 5.0.1 on 2024-09-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0032_rename_topic_compliancemeetingtopic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliancemeetingtopic',
            old_name='name',
            new_name='topic',
        ),
    ]
