# Generated by Django 5.0.1 on 2024-09-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0033_rename_name_compliancemeetingtopic_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemeetingquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='acr_tool.compliancemeetingtopic'),
        ),
    ]
