# Generated by Django 5.0.1 on 2024-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0034_alter_compliancemeetingquestion_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliancemeeting',
            old_name='questions',
            new_name='custom_questions',
        ),
        migrations.AddField(
            model_name='compliancemeeting',
            name='sample_questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RemoveField(
            model_name='compliancemeeting',
            name='topic',
        ),
        migrations.AddField(
            model_name='compliancemeeting',
            name='topic',
            field=models.ManyToManyField(related_name='compliance_meetings', to='acr_tool.compliancemeetingtopic'),
        ),
    ]
