# Generated by Django 5.0.1 on 2024-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0035_rename_questions_compliancemeeting_custom_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancemeeting',
            name='sample_questions',
        ),
        migrations.AddField(
            model_name='compliancemeeting',
            name='sample_questions',
            field=models.ManyToManyField(blank=True, related_name='compliance_meetings', to='acr_tool.compliancemeetingquestion'),
        ),
    ]
