# Generated by Django 5.0.1 on 2024-09-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0036_remove_compliancemeeting_sample_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancemeeting',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='compliancemeeting',
            name='custom_questions',
        ),
        migrations.RemoveField(
            model_name='compliancemeeting',
            name='topic',
        ),
        migrations.CreateModel(
            name='ComplianceMeetingTopicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_questions', models.JSONField(blank=True, default=list, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_details', to='acr_tool.compliancemeeting')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to='acr_tool.compliancemeetingtopic')),
            ],
        ),
        migrations.AddField(
            model_name='compliancemeeting',
            name='topics',
            field=models.ManyToManyField(related_name='compliance_meetings', through='acr_tool.ComplianceMeetingTopicDetail', to='acr_tool.compliancemeetingtopic'),
        ),
    ]
