# Generated by Django 5.0.1 on 2024-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0037_remove_compliancemeeting_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemeeting',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='compliance_meetings', through='acr_tool.ComplianceMeetingTopicDetail', to='acr_tool.compliancemeetingtopic'),
        ),
    ]
