# Generated by Django 5.0.1 on 2024-09-06 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0038_alter_compliancemeeting_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrulelinks',
            name='rule_files_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='regulatoryreview',
            name='section',
            field=models.CharField(choices=[('Final Rules', 'Final Rules'), ('Enforcement Actions', 'Enforcement Actions'), ('Risk Alerts', 'Risk Alerts'), ('Press Releases', 'Press Releases')], max_length=20),
        ),
        migrations.AlterField(
            model_name='secrulelinks',
            name='rule_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='secrulelinks',
            name='rule_name',
            field=models.CharField(choices=[('Final Rules', 'Final Rules'), ('Enforcement Actions', 'Enforcement Actions'), ('Risk Alerts', 'Risk Alerts'), ('Press Releases', 'Press Releases')], max_length=20),
        ),
    ]
