# Generated by Django 5.0.1 on 2024-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0039_secrulelinks_rule_files_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
