# Generated by Django 5.0.1 on 2024-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0040_alter_regulatoryreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentquestion',
            name='question_order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
