# Generated by Django 5.0.1 on 2024-09-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0041_riskassessmentquestion_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentsection',
            name='section_order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
