# Generated by Django 5.0.1 on 2024-09-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0042_riskassessmentsection_section_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policiesandprocedures',
            name='risk_questions',
        ),
        migrations.AddField(
            model_name='policiesandprocedures',
            name='risk_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acr_tool.riskassessmentquestion'),
        ),
    ]
