# Generated by Django 5.0.1 on 2024-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0043_remove_policiesandprocedures_risk_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policiesandprocedures',
            name='cco_updates_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policiesandprocedures',
            name='policies_procedure_tab',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policiesandprocedures',
            name='work_flow_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
