# Generated by Django 5.0.1 on 2024-09-23 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0044_policiesandprocedures_cco_updates_text_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_page', models.JSONField(blank=True, default=list, null=True)),
                ('introduction_page', models.JSONField(blank=True, default=list, null=True)),
                ('background_firm_narrative', models.TextField(blank=True, null=True)),
                ('overview_compliance_review_process', models.TextField(blank=True, null=True)),
                ('test_recommendation_next_year', models.TextField(blank=True, null=True)),
                ('blank_page', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
            ],
        ),
    ]
