# Generated by Django 5.0.1 on 2024-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0045_annualreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='cover_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='introduction_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
