# Generated by Django 5.0.1 on 2024-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0046_alter_annualreport_cover_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
