# Generated by Django 5.0.1 on 2024-10-02 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0049_annualreportresourcefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryresourcefile',
            name='created_by',
        ),
        migrations.CreateModel(
            name='AWSResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acr_tab', models.CharField(choices=[('Regulatory Review', 'Regulatory Review'), ('Risk Assessment', 'Risk Assessment'), ('Policies Procedures', 'Policies Procedures'), ('Procedure Review', 'Procedure Review'), ('Compliance Meeting', 'Compliance Meeting'), ('Annual Report', 'Annual Report')], max_length=20)),
                ('resource_file_s3_link', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AnnualReportResourceFile',
        ),
        migrations.DeleteModel(
            name='RegulatoryResourceFile',
        ),
    ]
