# Generated by Django 5.0.1 on 2024-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0050_remove_regulatoryresourcefile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsresourcefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
