# Generated by Django 5.0.1 on 2024-10-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0051_awsresourcefile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secrulelinks',
            name='rule_files_links',
        ),
    ]
