# Generated by Django 5.0.1 on 2024-10-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0053_remove_policiesandprocedures_regulatory_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighRiskQuestionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_all_high_risk_questions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('created_at',)},
            },
        ),
    ]
