# Generated by Django 5.0.1 on 2024-10-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0054_highriskquestionsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighRiskQuestionSettings',
        ),
    ]
