# Generated by Django 5.0.1 on 2024-10-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0061_annualreportinstructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessmentquestion',
            options={'verbose_name': 'Risk Assessment Question', 'verbose_name_plural': 'Risk Assessment Questions'},
        ),
        migrations.AlterModelOptions(
            name='riskassessmentsection',
            options={'verbose_name': 'Risk Assessment Section', 'verbose_name_plural': 'Risk Assessment Sections'},
        ),
        migrations.AlterField(
            model_name='riskassessmentquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acr_tool.riskassessmentsection'),
        ),
    ]
