# Generated by Django 5.0.1 on 2024-10-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0062_alter_riskassessmentquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='acr_tool.riskassessmentsection'),
        ),
    ]
