# Generated by Django 5.0.1 on 2024-10-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0063_alter_riskassessmentquestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandprocedures',
            name='regulatory_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acr_tool.regulatoryreview'),
        ),
        migrations.AlterField(
            model_name='policiesandprocedures',
            name='risk_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acr_tool.riskassessmentquestion'),
        ),
        migrations.AlterField(
            model_name='policiesandprocedures',
            name='risk_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acr_tool.riskassessmentsection'),
        ),
    ]
