# Generated by Django 5.0.1 on 2024-11-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0064_alter_policiesandprocedures_regulatory_review_and_more'),
        ('task', '0018_alter_task_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurereview',
            name='task',
        ),
        migrations.AddField(
            model_name='procedurereview',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
