# Generated by Django 5.0.1 on 2024-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0065_remove_procedurereview_task_procedurereview_task'),
        ('task', '0018_alter_task_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurereview',
            name='task',
        ),
        migrations.AddField(
            model_name='procedurereview',
            name='task',
            field=models.ManyToManyField(blank=True, to='task.task'),
        ),
    ]
