# Generated by Django 5.0.1 on 2024-11-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr_tool', '0067_policiesandprocedures_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policiesandprocedures',
            name='risk_question',
        ),
        migrations.RemoveField(
            model_name='policiesandprocedures',
            name='risk_section',
        ),
        migrations.AddField(
            model_name='policiesandprocedures',
            name='risk_assessment_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies_procedures', to='acr_tool.riskassessmentorgquestionresponse'),
        ),
    ]
